variant:
  id: tgv_id

  base_options:
    ep: https://togovar.biosciencedbc.jp/sparql
    sparqlist: https://togovar.biosciencedbc.jp/sparqlist

  stanza:
    - id: variant-header
      dom: "#variant-header"
      options:
        togostanza-menu-placement: none

    - id: variant-summary
      dom: "#variant-summary"

    - id: variant-other-overlapping-variants
      dom: "#variant-other-overlapping-variants"
      options:
        search_api: https://togovar.biosciencedbc.jp/search

    - id: variant-frequency
      dom: "#variant-frequency"

    - id: variant-clinvar
      dom: "#variant-clinvar"

    - id: variant-genomic-context
      dom: "#variant-genomic-context"
      options:
        assembly: GRCh37
        jbrowse: https://togovar.biosciencedbc.jp/jbrowse
        margin: 50

    - id: variant-gene
      dom: "#variant-gene"
      options:
        assembly: GRCh37

    - id: variant-transcript
      dom: "#variant-transcript"
      options:
        assembly: GRCh37

    - id: variant-publication
      dom: "#variant-publication"

gene:
  id:

  base_options:
    ep: https://togovar.biosciencedbc.jp/sparql
    sparqlist: https://togovar.biosciencedbc.jp/sparqlist

  stanza:
    - id: gene_base
      dom: "#gene_base"

    - id: gene_jbrowse
      dom: "#gene_jbrowse"

    - id: gene_variant
      dom: "#gene_variant"

    - id: gene_publication
      dom: "#gene_publication"

disease:
  id:

  base_options:
    ep: https://togovar.biosciencedbc.jp/sparql
    sparqlist: https://togovar.biosciencedbc.jp/sparqlist

  stanza:
    - id: disease_base
      dom: "#disease_base"

    - id: disease_variant
      dom: "#disease_variant"

    - id: disease_publication
      dom: "#disease_publication"
