defaults: &defaults
  sparql: <%= ENV.fetch('TOGOVAR_ENDPOINT_SPARQL') { '/sparql' } %>
  sparqlist: <%= ENV.fetch('TOGOVAR_ENDPOINT_SPARQLIST') { '/sparqlist' } %>
  search: <%= ENV.fetch('TOGOVAR_ENDPOINT_SEARCH') { '/search' } %>
  jbrowse: <%= ENV.fetch('TOGOVAR_ENDPOINT_JBROWSE') { '/jbrowse' } %>
  stanza: <%= ENV.fetch('TOGOVAR_ENDPOINT_STANZA') { '/stanza' } %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
