defaults: &defaults
  triplestore: https://togovar.biosciencedbc.jp/sparql
  sparqlist: https://togovar.biosciencedbc.jp/sparqlist/api

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
