defaults: &defaults
  container_1: <%= ENV['TOGOVAR_GTM_CONTAINER_1'] %>
  container_2: <%= ENV['TOGOVAR_GTM_CONTAINER_2'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
