defaults: &defaults
  server:
    url: http://dev.togogenome.org/stanza

  gene:
    nanostanza:
      -
        uri: http://togostanza.org/stanza/gene_length_nano
        span: 1
      -
        uri: http://togostanza.org/stanza/protein_ec_number_nano
        span: 1

    togostanza:
      -
        uri: http://togostanza.org/stanza/protein_names
        name: Protein names
      -
        uri: http://togostanza.org/stanza/gene_attributes
        name: Gene attributes

  clin_var:
    nanostanza: []

    togostanza:
      -
        name: clinvar_variant_information
        label: Variant Information
      -
        name: clinvar_variant_interpretation
        label: Variant Interpretation
      -
        name: clinvar_variant_alleles
        label: Variant Alleles

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
