defaults: &defaults
  server:
    url: http://dev.togogenome.org/stanza

  gene:
    nanostanza:
      -
        uri: http://togostanza.org/stanza/gene_length_nano
        span: 1
      -
        uri: http://togostanza.org/stanza/protein_ec_number_nano
        span: 1

    togostanza:
      -
        uri: http://togostanza.org/stanza/protein_names
        name: Protein names
      -
        uri: http://togostanza.org/stanza/gene_attributes
        name: Gene attributes

  clinvar:
    nanostanza: []

    togostanza:
      -
        name: clinvar_variant_information
        label: Variant Information
        params:
          -
            clinvar_id
      -
        name: clinvar_variant_interpretation
        label: Variant Interpretation
        params:
          -
            clinvar_id
      -
        name: clinvar_variant_alleles
        label: Variant Alleles
        params:
          -
            clinvar_id

  clinvar_allele:
    nanostanza: []

    togostanza:
      -
        name: clinvar_variant_information
        label: Variant Information
        params:
          -
            clinvar_id
      -
        name: clinvar_variant_interpretation
        label: Variant Interpretation
        params:
          -
            clinvar_id
      -
        name: clinvar_variant_alleles
        label: Variant Alleles
        params:
          -
            clinvar_id

  exac:
    nanostanza: []

    togostanza:
      exac_id:
        -
          name: exac_variant_information
          label: Variant Information
          params:
            -
              exac_id
        -
          name: exac_variant_annotations
          label: Variant Annotation
          params:
            -
              exac_id
        -
          name: exac_variant_population_frequencies
          label: Population Frequencies
          params:
            -
              exac_id
        -
          name: exac_variant_quality_histogram
          label: Quality Histogram
          params:
            -
              exac_id
      gene_id:
        -
          name: exac_gene_comparison_between_population
          label: Gene Comparison
          params:
            -
              gene_id
            -
              population1
            -
              threshold1
            -
              population2
            -
              threshold2
        -
          name: exac_gene_variant_list
          label: Variant List
          params:
            -
              gene_id

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
