defaults: &defaults
  providers:
    genes:
      nanostanza:
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/gene_length_nano
          span: 1
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_ec_number_nano
          span: 1
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_3d_structure_nano
          span: 1
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_references_timeline_nano
          span: 2

      togostanza:
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_names
          name: Protein names
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/genome_jbrowse
          name: Genomic context
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/gene_attributes
          name: Gene attributes
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/nucleotide_sequence
          name: Nucleotide sequence
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_attributes
          name: Protein attributes
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_sequence
          name: Protein sequence
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_general_annotation
          name: Protein general annotation
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_ontologies
          name: Protein ontologies
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_sequence_annotation
          name: Protein sequence annotation
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_pfam_plot
          name: Pfam plot
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_orthologs
          name: Protein orthologs
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_references
          name: Protein references
        -
          uri: http://ruby_stanza.togovar.l5dev.jp/stanza/protein_cross_references
          name: Protein cross references

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
