defaults: &defaults
  command: isql
  host: localhost
  port: 1111
  user: dba
  password:
  base_url: http://togovar.biosciencedbc.jp
  load_dir: /load

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: virtuoso
